package tetrix.entities.rotations;


/**
 * A cyclic enumeration of possible rotation states.
 * @author Dustin Biser
 *
 */
public enum RotationState {
	SPAWN_STATE, RIGHT_OF_SPAWN, SECOND_ROTATION, LEFT_OF_SPAWN;
	
	/**
	 * Get RotationState generated by a right (clockwise) rotation from current
	 * RotationState.
	 * @return RotationState
	 */
	public RotationState right(){
		return values()[ (ordinal() + 1) % values().length];
	}
	
	/**
	 * Get RotationState generated by a left (counter-clockwise) rotation from current
	 * RotationState.
	 * @return RotationState
	 */
	public RotationState left(){
		int index = ordinal() - 1;
		if ( index < 0) index = values().length - 1; 
		
		return values()[index];
	}
}
